CrudOperation/CrudOperation/urls.py
import imp
from django.contrib import admin
from django.urls import path, include
import engineerapp

urlpatterns = [     #sanırım buraya viewse eklediğimiz fonksiyonları giriyoruz
    path('', include('engineerapp.urls')),
    #path('engineerapp/', include('engineerapp.urls')),
    path('admin/', admin.site.urls),
    
]

CrudOperation/engineerapp/urls.py
from django.urls import path
from . import views

#bir appteysen appin adını giriyorsun, eğer ana appin altında bir appse de her hrefte önce app adı : <url name> kullanıyorsun
app_name = 'engineerapp'

#viewsta yazdığın fonksiyonlar için url düzenliyorsun
#sayfaya gidip bu fonksiyonları kullandığında pathin ilk parametresine gönderiyor bulunduğun adresten
#eğer herkes için aynıysa normal url yapıyorsun ama objeden objeye değişiyorsa /<int <views parametre adı> > yapıp dynamic url oluşturuyorsun
#3. parametre ise hrefte çağırdığında url pathini yazma diye unique bir isim koyuyorsun, htmlde hrefte {% %} arasına o isimle çağırabiliyorsun
#ve bu sayede dynamicleşiyor, bir şeyleri değiştirsen de url kısmında ismi aynı olduğundan her kullandığın templeteı da değiştirmene gerek kalmıyor
urlpatterns = [
    path('',views.home,name="home"), #name sayesinde bir şeyler değişse de templateta değiştirmene gerek kalmıyor daha dynamic oluyor
    path('engineer/<int:pk>',views.engineer,name='engineer'),
    path('insertEngineer/',views.insertEngineer,name='insertEngineer'), #ilki yukarıdaki linkin adı
    #<int: ya da <str dynamic yapıyor urli kişiye özgü oluyor yani edit/1 edit/2 gibi
    path('update/<int:engineer_id>',views.updateEngineer,name="updateEngineer"),
    path('delete/<int:engineer_id>',views.deleteEngineer,name="delete"),
    path('showLPs/',views.showlearningpaths, name="showlearningpaths"),  #yukarıdaki linkte yazan şey localhost .../showLPs/ gibi ilk parametre 
    path('showLPSteps/',views.showLPsteps, name="showLPsteps"), 
    path('createEngineerLearningPath/<str:pk>',views.createEngLP,name='createEngLP'),
    path('deleteEngineerLearningPath/<str:pk>',views.deleteEngLP,name='deleteEngLP'), 
    #{% url %} li kullanıyorsan name'i ile href =" "... diyorsan ilk parametreyle çağırıyorsun
    path('deleteEngineerLearningPathStep/<str:pk>',views.deleteEngLPStep,name='deleteEngLPStep'),

    path('register/',views.registerPage,name='registerPage'),
    path('login/',views.loginPage,name='loginPage'),
    path('logout/',views.logoutUser,name='logout'),
    path('user/',views.UserPage,name='user-page') ,
    path('createEngLPS/<str:pk>/<str:lpk>',views.createEngLPS,name='createEngLPS'),
    path('home/',views.mainPage,name="mainPage"),
    path('edit/', views.editEngineer, name="editEngineer"),
    path('accreditation/<str:pk>/<str:lpk>',views.createAcc, name="createAccreditation"),
    path('deleteAccreditation/<str:pk>',views.deleteAcc,name="deleteAcc"),
    path('LearningPaths',views.notuserlp,name="notuserlp"),
    path('LearningPathSteps',views.notuserLPsteps,name="notuserLPsteps"),
    path('Home/',views.userhome,name="userhome"),
]

CrudOperation/engineerapp/forms.py
from dataclasses import field
import imp
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from engineerapp.models import *   #update i yarattıktan sonra kurduk

#forms sayesinde admin gibi kendi kendine alan yaratmadan viewsa çekerek form oluşturmuş oluyorsun modeldeki parametrelerle
class EngForms(forms.ModelForm):
    class Meta:
        model=EngModel
        fields="__all__"  #bu Engmodel altındaki tüm fieldları eng_id ve name i kapsıyor yani ??

class EngLPForms(forms.ModelForm):  
    class Meta:
        model = EngLPModel
        fields = "__all__"

class AccForm(forms.ModelForm):
    class Meta:
        model = AccreditationModel
        fields = "__all__"
    
class EngLPStepForms(forms.ModelForm):
    class Meta:
        model = EngLPStepModel
        fields = "__all__"
        exclude = ['completed',]    # I exclude it because, if we add the step we must be complete that necessity.

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2'] #confirmation pw 


class LPSForm(forms.ModelForm): #dynamic form denedim ama yine olmadı
    def __init__(self,learningpath,*args,**kwargs):
        super (LPSForm,self ).__init__(*args,**kwargs) # populates the post
        self.fields['lp_step'].queryset = LPStepsModel.objects.filter(learningpath=learningpath)
        self.fields['learningpath'].queryset = LPModel.objects.filter(learningpath=learningpath)

    class Meta:
        model = EngLPStepModel
        fields = "__all__"

CrudOperation/engineerapp/views.py
from multiprocessing import context
import re
from tokenize import Name
from django.contrib.auth.forms import UserCreationForm
from turtle import isvisible
from unicodedata import name
from django.shortcuts import get_object_or_404, redirect, render #biz olusturduk
from engineerapp.models import *
from django.contrib import messages
from django.http import HttpResponseRedirect
from engineerapp.forms import *
from .filters import *
from django.forms import inlineformset_factory  #inline formset için 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import *
from django.contrib.auth.models import Group

#burası sayfada kullanacağın fonksiyonları yazdığın sayfa
#fonksiyonlarda genelde modellerden objeleri çekersin ve en son renderda request,'görüneceği sayfa' ve çektiğin objelerle returnlersin
#methodun POST olması bu fonksiyonun linkle bir yerlere gidip gitmeyeceğiyle alakalı sanırım ?


usercreated = False

def doesitcreated(x):   #if user created we call this function with parameter 1, and it makes usercreated True
    global usercreated
    if x == 1:
        usercreated = True
    else:   #else make it false
        usercreated = False

def mainPage(request):  #home page for guests
    return render(request,'home.html',{})

@login_required(login_url='engineerapp:loginPage')
@allowed_users(allowed_groups=['admin','engineer']) 
def userhome(request):  #home page for users I split them because their navbars are different. I prevent some kind of unwanted things for doing this.
    return render(request,'userhome.html',{})


@unauthenticated_user
def registerPage(request): #UserCreationForm imported
    #form = UserCreationForm()        #that was defaulted form, to shape it as we want we create a form in forms.py
    form = UserForm()
    if request.method == "POST":    
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()  #similar to other forms saving process
            username = form.cleaned_data.get('username')    #calling the username, cleaned_data is for reducing the errors.
            group = Group.objects.get(name='engineer')  #calling the engineer group
            user.groups.add(group)      #thanks to this, whenever a user is created it automatically become an engineer.
            EngModel.objects.create(
                user=user,  #there wasn't enough user_id in my database therefore I add 100 user_id manually, if it exceed that they will be an error.
                ) #this is for OneToOneField in EngModel, it creates a user for this model.
            #logeduser= authenticate(request, user)
            #login(request, logeduser)
            #return redirect('engineerapp:loginPage')
            doesitcreated(1)    #because we create user we call that function with 1
            messages.success(request, 'User ' + username + ' created successfully! ')      
            return redirect('engineerapp:loginPage')    #it redirects to the login page

    context={'form':form}
    return render(request,'register.html',context)


@unauthenticated_user
def loginPage(request):
    
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
            
        user = authenticate(request, username=username, password=password)  #it checks whether thee user is valid
        
        if user is not None:    #if there exist a user in database  
            login(request, user)    #it logs in, because its name is login I created that function name different from that.
            if (usercreated):   #if it's created now, first name its engineer object
                doesitcreated(0)      #because we use creation we make it false again
                return redirect('engineerapp:editEngineer')
            else:               #else redirect to the home (User) page
                return redirect('engineerapp:home')
        else:
            messages.info(request, 'username or password is incorrect!')

    context={}
    return render(request,'login.html',context)

def logoutUser(request):
    logout(request) #it logs out.
    return redirect('engineerapp:loginPage')    #it redirects to the loginPagee, bunu navbara ekledik
    #ama user loginlemediğinde de navbarda anonymous çıkıyor ve logout oluyor bunun olmasını istemiyoruz
    #bu yüzden girebilmek için login gerekli yerler yapacağız @ ile functionın üstünde login çıkacak

@login_required(login_url='engineerapp:loginPage')  #only the user can see that page, guest cannot see this page.
@allowed_users(allowed_groups=['engineer',])    #only a user that has a group engineer can see the user page other group users cannot see this page.
def UserPage(request):   
    currEngineer = request.user.engmodel    #because there was a 1-1 relationship between user and engmodel, it calls the engineer from the user.
                                            #however, the modelname should be lower case.
    englps = currEngineer.englpmodel_set.all() 
    englpsteps = currEngineer.englpstepmodel_set.all() 
    accreditations = currEngineer.accreditationmodel_set.all()
    lpcount = englps.count()   
    lpstepcount = englpsteps.count() 
    context={'engineer':currEngineer, 'LP':englps, 'LPStep':englpsteps,'LP_count':lpcount,'LPStep_count':lpstepcount,'accreditations':accreditations}
    return render(request,'user.html',context)

#önce logine bakar sonra allowed usera bakar o yüzden bu sırayla
#@login_required(login_url='engineerapp:loginPage')  #login olmadan girememek için yoksa anonymoususer çıkar, bunu her girebildiğimiz urle yapacağız
@send_userpage  #that function defines in decorators, basically it redirects engineer group user to the user-page, it allows the admin to view that page
def home(request):
    engineers=EngModel.objects.all() #it's getting all engineers
    engineerLp = EngLPModel.objects.all()  #it's getting all engineer learning paths
    engineerLPSteps = EngLPStepModel.objects.all() #it's getting all engineers learning path steps
    accs = AccreditationModel.objects.all()
    context = {"data":engineers,"EngLP":engineerLp,"EngLPSteps":engineerLPSteps, "accs":accs} #give them a name to use those in html file
    return render(request,'index.html',context)



@login_required(login_url='engineerapp:loginPage')
@allowed_users(allowed_groups=['admin','engineer']) 
def engineer(request, pk):  #request and pk parameters we used pk as the engineers id
    currEngineer = EngModel.objects.get(engineer_id = pk) #find the current engineer whose id is equal to pk
    englps = currEngineer.englpmodel_set.all() #that's a special function which gets all learningpaths of the currentEngineer
    englpsteps = currEngineer.englpstepmodel_set.all() #it's like the englps
    lpcount = englps.count()    #it counts the englps
    lpstepcount = englpsteps.count() #it counts the englpsteps
    LearningPathFilter = LPFilter(request.GET, queryset=englps)     #it defined in filter.py 
    #request.GET is necessary for this function, querysetse bu tüm objelerin 
    #filter is defined which function(page) that will be used, you specify which fields to be filtered in filter.py
    englps = LearningPathFilter.qs  #thanks to this only the filtered datas can be shown in page.

    context = {'engineer':currEngineer, 'LP':englps, 'LPStep':englpsteps,'LP_count':lpcount,'LPStep_count':lpstepcount,
     'LPFilt':LearningPathFilter}
    return render(request, 'engineer.html', context)

            
#@login_required(login_url='engineerapp:loginPage')
#@allowed_users(allowed_groups=['admin',]) 
def showlearningpaths(request): #it shows the learning paths and learning path steps
    lp=LPModel.objects.all()
    lps = LPStepsModel.objects.all()
    context = {"LPvalues":lp, "LPSteps":lps}
    return render(request, 'LP.html', context )

def notuserlp(request): #it shows the learning paths and learning path steps
    lp=LPModel.objects.all()
    lps = LPStepsModel.objects.all()
    context = {"LPvalues":lp, "LPSteps":lps}
    return render(request, 'notuserLP.html', context )

#@login_required(login_url='engineerapp:loginPage')
#@allowed_users(allowed_groups=['admin',]) 
def showLPsteps(request):
    showall=LPStepsModel.objects.all()
    return render(request, 'LPSteps.html', {"LPSteps":showall} )

def notuserLPsteps(request):
    showall=LPStepsModel.objects.all()
    return render(request, 'notuserLPS.html', {"LPSteps":showall} )

@login_required(login_url='engineerapp:loginPage')
@allowed_users(allowed_groups=['admin','engineer']) 
def insertEngineer(request):    #that function is for creating an engineer, I didn't make it with forms because I didn't learn it when I create this func.
    if request.method=="POST":     #I keep this because it's a good remainder for me to creating an object without form.
        if request.POST.get('name') :    # if it has a name
            saverecord=EngModel()   
            saverecord.name=request.POST.get('name')    #gets the name
            saverecord.save()    #and save it successfully!
            return redirect('/') #whenever an engineer created it returns to the home page
    return render(request,'insert.html',{})

@login_required(login_url='engineerapp:loginPage')
@allowed_users(allowed_groups=['admin','engineer']) 
def updateEngineer(request,engineer_id):    #it's for admin, we will delete it once we finish the project
    updateEng = EngModel.objects.get(engineer_id=engineer_id)
    form = EngForms(instance=updateEng) 
    currUser = request.user
    if request.method == "POST":
        form = EngForms(request.POST,instance=updateEng) 
        if form.is_valid(): 
            form.save()
            return redirect('/')

CrudOperation/engineerapp/templates/EngLPStep.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-md">
		<div class="card card-body">
			<h5> {{message}}</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{remainingsteps}}</h1>
		</div>
	</div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    {{form}}

    <div class="row"> 
        <input style="margin-left: 10px;" type="submit" name="Submit">
        {% if request.user.is_staff %}  <!-- to see the admin -->
        <a style="margin-left: 10px;" class="btn btn-warning" href="{% url 'engineerapp:engineer' engineer.engineer_id %}"> Back to the Engineer Page </a>
        {% endif %}
        {% if not request.user.is_staff %}  <!-- to see the user -->
        <a style="margin-left: 10px;" class="btn btn-warning" href="{% url 'engineerapp:user-page' %}"> Back to the User Page </a>
        {% endif %}
    </div>


</form>


{% endblock %}

CrudOperation/engineerapp/templates/accreditation.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-md">
		<div class="card card-body">
			<h5> {{message}}</h5>
		</div>
	</div>
</div>

<form action="" method="POST">
    {% csrf_token %}
    {{form}}

    <div class="row"> 
        <input style="margin-left: 10px;" type="submit" name="Submit">
        <a style="margin-left: 10px;" class="btn btn-warning" href="{% url 'engineerapp:engineer' engineer.engineer_id %}"> Back to the Engineer Page </a>
    </div>


</form>


{% endblock %}

CrudOperation/engineerapp/templates/delete.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item.name}}"?</p>

			<form action="{% url 'engineerapp:delete' item.engineer_id  %}" method="POST">  
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'engineerapp:home' %}">Cancel</a>

				<input class="btn btn-danger" name="Confirm" type="submit" > <!-- Confirm değil gönder çıkıyor submiti çeviriyor niyeyse-->
			</form>
		</div>
	</div>
</div>

{% endblock %}

CrudOperation/engineerapp/templates/deleteEngLPStep.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'engineerapp:deleteEngLPStep' item.englpstep_id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'engineerapp:home' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

CrudOperation/engineerapp/templates/editengineer.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<h4> Please Customize Your Engineer Name {{user}}</h4>

<form action="" method="POST">

    {% csrf_token %}
    {{form}}

    <div class="row"> 
        <input style="margin-left: 20px;" type="submit" name="Submit">
        <a class="btn btn-warning" href="{% url 'engineerapp:home' %}"> Back to the Home Page</a>
    </div>

</form>


{% endblock %}

CrudOperation/engineerapp/templates/engLP.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<h3 style="color: purple;"> Welcome {{engineer.name}} !</h3>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<form action="" method="POST">
				
				{% csrf_token %}
				<!-- 
				{{ form.management_form }}	<!-- loopta individually bakması gerektiğini söylemek için management_form lazım-->
				<!-- {% for field in form %}
					{{field}}
					<hr>
				{% endfor %} -->
				{{form}}
				
				<div class="row"> 
					<input type="submit" name="Submit">
				{% if request.user.is_staff %}  <!-- to see the admin -->
        		<a style="margin-left: 10px;" class="btn btn-warning" href="{% url 'engineerapp:engineer' engineer.engineer_id %}"> Back to the Engineer Page </a>
        		{% endif %}
        		{% if not request.user.is_staff %}  <!-- to see the user -->
        		<a style="margin-left: 10px;" class="btn btn-warning" href="{% url 'engineerapp:user-page' %}"> Back to the User Page </a>
        		{% endif %}
				</div>
			</form>

		</div>
	</div>
</div>

{% endblock %}

CrudOperation/engineerapp/templates/index.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <center>
        
            
        <div class="row"> 
            <div class="col-md-5">
                <div class="card card-body">
                    <h1 style="color: navy;">
                        Engineer Table
                    </h1>
                    <a class="btn btn-primary btn-sm btn-block" href="{% url 'engineerapp:insertEngineer' %}"> Create New Engineer</a>
                    <table class="table table-sm">
                        <tr>
                            <!--<th>Engineer ID</th>-->
                            <th>    </th>
                            <th>Engineer Name</th>
                        </tr>
                        {% for result in data%}     <!-- data ismi viewstan geldi --> 
                        <tr>
                            <!--<td>{{result.engineer_id}}</td>--> 
                            <td><img src="{% static 'images/engineeremoji.jpg' %}"></td>
                            <td>{{result.name}}</td>
                            <td><a class="btn btn-sm btn-info"  href="{% url 'engineerapp:updateEngineer' result.engineer_id %}" > Edit </a> </td>
            <!--<td><a class="btn btn-sm btn-danger" href="delete/{{result.engineer_id}}" onclick="return confirm('Are you sure ?')" > Delete </a></td>-->
                            <td><a class="btn btn-sm btn-danger" href="delete/{{result.engineer_id}}"> Delete </a></td>                        
                            <!--onclick is a simple JavaScript func-->
                            <td><a class="btn btn-sm btn-info" href="engineer/{{result.engineer_id}}"> See Learning Paths</a></td>
                        </tr>
                        {% endfor%}                 <!--for loop bitiriyor-->   
                    </table>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card card-body">
                    <h2 style="color: navy;">
                        Accreditation Table
                    </h2>
                    <table class="table table-sm">
                        <tr>
                            <th>Engineer Name</th>
                            <th>MIP Name</th>
                        </tr>
                        {% for accreditation in accs %}     
                        <tr>
                            <td>{{accreditation.engineer}}</td>
                            <td>{{accreditation.mip}}</td>
                            <td><a class="btn btn-sm btn-danger" href="{% url 'engineerapp:deleteAcc' accreditation.acc_id %}"> Delete </a></td>
                        </tr>
                        {% endfor%}                 
                    </table>
                </div>
            </div>
        </div>


        <div class="row">    
            <div class="col-md-5">
                <div class="card card-body">
                    <h2 style="color: navy;">
                        Engineer Learning Path Table
                    </h2>
                    <table class="table table-sm">
                        <tr>
                            <th>Engineer Name</th>
                            <th>Learning Path</th>
                        </tr>
                        {% for engLP in EngLP %}     <!-- data ismi viewstan geldi --> 
                        <tr>
                            <td>{{engLP.engineer}}</td>
                            <td>{{engLP.learningpath}}</td>
                        </tr>
                        {% endfor%}                 <!--for loop bitiriyor-->   
                    </table>
                </div>
            </div>

            <div class="col-md-5">
                <div class="card card-body">
                    <h2 style="color: navy;">
                        Completed Engineer Learning Path Step Table
                    </h2>
                    <table class="table table-sm">
                        <tr>
                            <th>Engineer Name</th>
                            <th>Learning Path Step</th>
                        </tr>
                        {% for engLPS in EngLPSteps %}     
                        <tr>
                            <td>{{engLPS.engineer}}</td>
                            <td>{{engLPS.lp_step}}</td>
                        </tr>
                        {% endfor%}                 
                    </table>
                </div>
            </div>
        </div>


    </center>

{% endblock %}


CrudOperation/engineerapp/templates/insert.html
{% extends 'main.html' %}

{% block content %}
    <center>
        <h1 style="color: violet;">
            Insert Record Into PSQL
        </h1>
        <hr/>
        <form method="POST">
            {% csrf_token %}    <!-- in django it protects our data from hackers when we posted it, bu yoksa error alıyormuş? --> 
            <table border="1">
                <tr>        <!-- eng_id yi girmedik gerekecek mi bak ona -->
                    <td> Engineer Name </td>    <!--bura başlık gibi-->
                    <td> <input type="text" placeholder="Enter Engineer Name" name="name">    </td>  <!--name i viewstaki namein aynısı yapmalısın--> 
                </tr>
                <tr>
                    <td><input type="submit" value="Insert" /></td>
                </tr>
            </table>
    </form>
    </center>
    
{% endblock %}

CrudOperation/engineerapp/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <style>
        .tab4{
            tab-size: 4;
        }   
    </style>

</head>
<body>
    
    {% include 'navbar.html' %} <!-- navbarı dahil ettik burada-->

    <!-- maini her templeteta kullancağımızdan block arasındaki kısım diğer templetelarda yazılacakları ifade ediyor main parent yani-->
    {% block content %}


    {% endblock %}

    <hr>

</body>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

CrudOperation/engineerapp/templates/navbar.html
{% load static %} <!-- need for every single html -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!--<a class="navbar-brand" href="#">Navbar</a>-->  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'engineerapp:userhome' %}"> Home <span class="sr-only">(current)</span></a>
        </li>
        {% if request.user.is_staff %}  <!-- attribute gibi admin attribute u varsa gösterir navbarı -->
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'engineerapp:home' %}"> Main Page <span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        {% if not request.user.is_staff %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'engineerapp:user-page' %}"> User Page <span class="sr-only">(current)</span></a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'engineerapp:showlearningpaths' %}"> Learning Paths </a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'engineerapp:showLPsteps' %}"> Learning Path Steps </a>
        </li>
        
      </ul>
    </div>

    {% if request.user.is_staff %}
    <span style="color: white; margin-right: 20px;" >  {{request.user}} (Admin) </span>
    {% endif %}
    {% if not request.user.is_staff %}
    <span style="color: white; margin-right: 20px;" >  {{request.user}} (Engineer) </span>
    {% endif %}
    <span style="color: white; margin-right: 20px;"> <a href="{% url 'engineerapp:logout' %}"> Logout </a></span>

  </nav>

CrudOperation/engineerapp/templates/notusernavbar.html
{% load static %} <!-- need for every single html -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!--<a class="navbar-brand" href="#">Navbar</a>-->  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'engineerapp:mainPage' %}"> Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'engineerapp:notuserlp' %}"> Learning Paths </a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'engineerapp:notuserLPsteps' %}"> Learning Path Steps </a>
        </li>
        
      </ul>
    </div>

    <span style="color: white; margin-right: 20px;" >  {{request.user}}  </span>
    <span style="color: white; margin-right: 20px;"> <a href="{% url 'engineerapp:logout' %}"> Logout </a></span>

  </nav>